language: python
python:
  - '3.9'

before_script:
  - pip install -r requirements.txt
  - wget https://msedgedriver.azureedge.net/93.0.961.33/edgedriver_linux64.zip
  - unzip edgedriver_linux64.zip
  - sudo mv edgedriver /usr/local/bin
  - psql -c 'create database purbeurre;' -U postgres

env: DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"

services:
  - postgresql

script:
  - python manage.py test

branches:
  only:
    - staging