language: python
python:
  - '3.9'

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database purbeurre;' -U postgres

env: DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"

services:
  - postgresql

script:
  - python manage.py test supersub/tests/unit/management/