language: python
python:
  - '3.9'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"

services:
  - postgresql

addons:
  postgresql: "13"

script:
  - python manage.py test supersub/tests/unit/management/